controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_login:
    path: /login
    controller: App\Controller\LoginController::login

app_logout:
    path: /logout
    controller: App\Controller\LoginController

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
